spring:
  # H2-DB setting
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
  datasource:
    url: jdbc:mysql://bingx-rds.c1hjri6ln58w.ap-northeast-2.rds.amazonaws.com/bingx_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 2db8ddasf!
  # JPA setting
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  # thymeleaf PUT, DELETE Method use
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    web:
      pageable:
        default-page-size: 10

#S3
cloud:
  aws:
    credentials:
      instanceProfile: true
      accessKey: AKIARY3466IHV5LQXTAG
      secretKey: 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
    s3:
      bucket: bingx-image
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false